"""empty message

Revision ID: 693ed5c5d791
Revises:
Create Date: 2019-09-24 16:21:06.160586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean, String
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = '693ed5c5d791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_status',
                    sa.Column('code', sa.String(length=15), nullable=False),
                    sa.Column('desc', sa.String(length=100), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('code')
                    )
    op.create_table('notification_type',
                    sa.Column('code', sa.String(length=15), nullable=False),
                    sa.Column('desc', sa.String(length=100), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('code'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recipients', sa.String(length=2000), nullable=False),
                    sa.Column('request_date', sa.DateTime(), nullable=False),
                    sa.Column('sent_date', sa.DateTime(), nullable=True),
                    sa.Column('type_code', sa.String(length=15), nullable=False),
                    sa.Column('status_code', sa.String(length=15), nullable=False),
                    sa.ForeignKeyConstraint(['status_code'], ['notification_status.code'], ),
                    sa.ForeignKeyConstraint(['type_code'], ['notification_type.code'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    notification_type_table = table('notification_type',
                                    column('code', String),
                                    column('desc', String),
                                    column('default', Boolean)
                                    )

    op.bulk_insert(
        notification_type_table,
        [
            {'code': 'EMAIL', 'desc': 'The Email type of notification', 'default': True},
            {'code': 'TEXT', 'desc': 'The Text message type of notification', 'default': False}
        ]
    )

    # Insert codes and descriptions for organization status
    notification_status_table = table('notification_status',
                                      column('code', String),
                                      column('desc', String),
                                      column('default', Boolean)
                                      )
    op.bulk_insert(
        notification_status_table,
        [
            {'code': 'PENDING', 'desc': 'Initial state of the notification', 'default': True},
            {'code': 'SUCCESS', 'desc': 'Status for the notification sent successful', 'default': False},
            {'code': 'FAILURE', 'desc': 'Status for the notification sent failuree', 'default': False}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('notification_type')
    op.drop_table('notification_status')
    # ### end Alembic commands ###
