---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-${TAG}-deployment-template
  annotations:
    description:
      Deployment template for an API application and connect to database.
    tags: Flask
    iconClass: icon-python
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}-to-external
      labels:
        name: ${NAME}-${TAG}-to-external
        app: ${NAME}
    spec:
      description: |
        Allow the application's service to talk to external resources.
      source:
        - - role=${ROLE}
          - app=${NAME}
          - $namespace=${NAMESPACE}-${TAG}
      destination:
        - - ext:name=${NAME}-external

  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}-to-db
      labels:
        name: ${NAME}-${TAG}
        app: ${NAME}
    spec:
      description: |
        Allow the application's service to talk to the database.
      source:
        - - role=${ROLE}
          - app=${NAME}
          - $namespace=${NAMESPACE}-${TAG}
      destination:
        - - role=db
          - app=${DB_NAME}
          - $namespace=${NAMESPACE}-${TAG}

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}-${TAG}
        app: ${NAME}
        role: ${ROLE}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: "[{name: ${DB_NAME}-${TAG}, kind: Service}]"
    spec:
      ports:
        - name: ${NAME}-${TAG}-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}-${TAG}

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}-${TAG}
        app: ${NAME}
        role: ${ROLE}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-${TAG}
            from:
              kind: ImageStreamTag
              namespace: ${NAMESPACE}-${IMAGE_NAMESPACE}
              name: ${NAME}:${TAG}
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}-${TAG}
      template:
        metadata:
          name: ${NAME}-${TAG}
          labels:
            name: ${NAME}-${TAG}
            app: ${NAME}
            role: ${ROLE}
        spec:
          containers:
            - name: ${NAME}-${TAG}
              image:
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 3
                timeoutSeconds: 30
                httpGet:
                  path: /readyz
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 120
                timeoutSeconds: 30
                httpGet:
                  path: /healthz
                  port: 8080

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        name: ${NAME}-${TAG}
        app: ${NAME}
        role: ${ROLE}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${NAME}-${TAG}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: account-mailer

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: queue

  - name: NAMESPACE
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: 6e0e49

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: tools

  - name: DB_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: postgresql

  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "1"

  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "1"

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m

  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi

  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
