# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The Network Security Policies (KNP) for the associated
      BC Registries Nats service.
  name: knp-${NAME}-templates
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-to-db
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the Nats service communitcated with postgresql database.
      podSelector:
        matchLabels:
          role: ${ROLE_DB}
      ingress:
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_NATS}
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-lear-to-nats
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the lear namespace api, queue and job pods communitcated with Nats service.
      podSelector:
        matchLabels:
          role: ${ROLE_NATS}
      ingress:
        - ports:
            - protocol: TCP
              port: 4222
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_LEAR}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_LEAR}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_LEAR}
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-auth-to-nats
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the auth namespace api and queue pods communitcated with Nats service.
      podSelector:
        matchLabels:
          role: ${ROLE_NATS}
      ingress:
        - ports:
            - protocol: TCP
              port: 4222
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_AUTH}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_AUTH}
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-pay-to-nats
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the pay namespace api and queue pods communitcated with Nats service.
      podSelector:
        matchLabels:
          role: ${ROLE_NATS}
      ingress:
        - ports:
            - protocol: TCP
              port: 4222
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_PAY}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_PAY}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_PAY}
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-names-to-nats
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the names namespace api and queue pods communitcated with Nats service.
      podSelector:
        matchLabels:
          role: ${ROLE_NATS}
      ingress:
        - ports:
            - protocol: TCP
              port: 4222
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_NAMES}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_NAMES}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
              namespaceSelector:
                matchLabels:
                  environment: ${TAG}
                  name: ${NAMESPACE_NAMES}
      policyTypes:
        - Ingress

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: nats-streaming

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE_NATS
    displayName: Role
    description: Role
    required: true
    value: nats

  - name: ROLE_DB
    displayName: Role
    description: Role
    required: true
    value: db

  - name: ROLE_API
    displayName: Role
    description: Role
    required: true
    value: api

  - name: ROLE_JOB
    displayName: Role
    description: Role
    required: true
    value: job

  - name: ROLE_QUEUE
    displayName: Role
    description: Role
    required: true
    value: queue

  - name: NAMESPACE_AUTH
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: 6e0e49

  - name: NAMESPACE_LEAR
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: cc892f

  - name: NAMESPACE_PAY
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: 78c88a

  - name: NAMESPACE_NAMES
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: f2b77c
