# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The Network Security Policies (KNP) for the associated
      BC Registries applications.
  name: bcrs-knp-templates
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow external access (route) to this namespace.
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-to-db
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the api, hook-pre,, keycloak, backup, queue and job pods communitcated with db pods.
      podSelector:
        matchLabels:
          role: ${ROLE_DB}
      ingress:
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
            - podSelector:
                matchLabels:
                  role: ${ROLE_KEYCLOAK}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
            - podSelector:
                matchLabels:
                  role: ${ROLE_BACKUP}
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-pre
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-to-api
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the api, queue and job pods communitcated with other api pods.
      podSelector:
        matchLabels:
          role: ${ROLE_API}
      ingress:
        - ports:
            - protocol: TCP
              port: 8080
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
      policyTypes:
        - Ingress

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-to-mailhog
      labels:
        name: ${NAME}
        environment: ${TAG}
    spec:
      description: |
        allow the api, queue and job pods communitcated with mailhog service.
      podSelector:
        matchLabels:
          app: mailhog
      ingress:
        - ports:
            - protocol: TCP
              port: 1025
          from:
            - podSelector:
                matchLabels:
                  role: ${ROLE_API}
            - podSelector:
                matchLabels:
                  role: ${ROLE_QUEUE}
            - podSelector:
                matchLabels:
                  role: ${ROLE_JOB}
      policyTypes:
        - Ingress

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: sbc-auth

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE_DB
    displayName: Role
    description: Role
    required: true
    value: db

  - name: ROLE_API
    displayName: Role
    description: Role
    required: true
    value: api

  - name: ROLE_JOB
    displayName: Role
    description: Role
    required: true
    value: job

  - name: ROLE_QUEUE
    displayName: Role
    description: Role
    required: true
    value: queue

  - name: ROLE_KEYCLOAK
    displayName: Role
    description: Role
    required: true
    value: keycloak

  - name: ROLE_BACKUP
    displayName: Role
    description: Role
    required: true
    value: backup

