apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The Network Security Policies (NSP) for the associated BC registry application.
  name: ${NAME}-nsp
objects:
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: ${NAME}-to-db
      labels:
        app: ${APP}
    spec:
      description: |
        allow the backup container to communicate with the db and rocketchat.
      source:
        - - "role=backup"
          - "$namespace=${NAMESPACE}"
      destination:
        - - "role=db"
          - "$namespace=${NAMESPACE}"
        - - "ext:name=rocketchat"
parameters:
  - name: NAMESPACE
    description: |
      The the name of the namespace the policy is being
      deployed to.
    required: true
    value: 6e0e49
  - name: NAME
    description: |
      The the name of the namespace the policy is being
      deployed to.
    required: true
    value: backup
