"""add account_id and relationship_status columns in tasks table

Revision ID: 031a07fb0811
Revises: 885632ab6357
Create Date: 2021-04-14 17:48:33.958394

"""
from alembic import op
import sqlalchemy as sa
from auth_api.utils.enums import TaskRelationshipStatus


# revision identifiers, used by Alembic.
revision = '031a07fb0811'
down_revision = '885632ab6357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('relationship_status', sa.String(length=100), nullable=True,
                                     server_default=TaskRelationshipStatus.PENDING_STAFF_REVIEW.value))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'account_id')
    op.drop_column('tasks', 'relationship_status')
    # ### end Alembic commands ###
