"""payment_settings_changes

Revision ID: 06eda339e0d5
Revises: 09c44f82c03c
Create Date: 2020-03-25 16:49:14.477141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eda339e0d5'
down_revision = '09c44f82c03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_payment_settings',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferred_payment_code', sa.String(length=15), nullable=False),
    sa.Column('bcol_user_id', sa.String(length=20), nullable=True),
    sa.Column('bcol_account_id', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['preferred_payment_code'], ['payment_type.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_access_type'), 'org', ['access_type'], unique=False)
    op.drop_constraint('org_preferred_payment_code_fkey', 'org', type_='foreignkey')
    op.drop_column('org', 'preferred_payment_code')

    ## Insert default values for all orgs
    op.execute("insert into account_payment_settings (org_id, preferred_payment_code) select id, 'CC' FROM org")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('preferred_payment_code', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_foreign_key('org_preferred_payment_code_fkey', 'org', 'payment_type', ['preferred_payment_code'], ['code'])
    op.drop_index(op.f('ix_org_access_type'), table_name='org')
    op.drop_table('account_payment_settings')
    # ### end Alembic commands ###