"""org_api_access

Revision ID: 129eb4978d07
Revises: 2d71e7d7cc18
Create Date: 2021-03-26 13:09:16.230695

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '129eb4978d07'
down_revision = '2d71e7d7cc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('has_api_access', sa.Boolean(), nullable=True))
    op.add_column('orgs_version', sa.Column('has_api_access', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs_version', 'has_api_access')
    op.drop_column('orgs', 'has_api_access')
    # ### end Alembic commands ###
