"""migrating for prod

Revision ID: 18a4955730f9
Revises: 06c7acc047fa
Create Date: 2020-10-22 17:05:30.367190

"""

# revision identifiers, used by Alembic.
revision = '18a4955730f9'
down_revision = '06c7acc047fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

