"""keycloak_guid made nullable

Revision ID: 19ffc2fcc88c
Revises: 68e2f43b9d22
Create Date: 2020-03-24 10:36:57.439832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19ffc2fcc88c'
down_revision = '68e2f43b9d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'keycloak_guid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'keycloak_guid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
