"""permissons for activity log

Revision ID: 1a46fdc4d630
Revises: a0f0a77dc77f
Create Date: 2021-05-04 10:15:37.494139

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table

from auth_api.utils.custom_sql import CustomSql


# revision identifiers, used by Alembic.
revision = "1a46fdc4d630"
down_revision = "a0f0a77dc77f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table(
        "permissions",
        column("id", sa.Integer()),
        column("membership_type_code", sa.String(length=15)),
        column("org_status_code", sa.String(length=25)),
        column("actions", sa.String(length=100)),
    )

    conn = op.get_bind()
    res = conn.execute(text(f"select max(id) from permissions;"))
    latest_id = res.fetchall()[0][0]

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {
                "id": latest_id + 1,
                "membership_type_code": "ADMIN",
                "org_status_code": None,
                "actions": "view_activitylog",
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    op.execute('delete from permissions where action="view_activitylog"')
    # ### end Alembic commands ###
