"""empty message

Revision ID: 1ddf3b37e17f
Revises: 98bee9969323
Create Date: 2023-09-05 11:33:50.692272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddf3b37e17f'
down_revision = '98bee9969323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliations', sa.Column('environment', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_affiliations_environment'), 'affiliations', ['environment'], unique=False)
    op.add_column('affiliations_version', sa.Column('environment', sa.String(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_affiliations_version_environment'), 'affiliations_version', ['environment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliations_version_environment'), table_name='affiliations_version')
    op.drop_column('affiliations_version', 'environment')
    op.drop_index(op.f('ix_affiliations_environment'), table_name='affiliations')
    op.drop_column('affiliations', 'environment')
    # ### end Alembic commands ###
