"""Add uuid column to orgs table.

Revision ID: d53a79e9cc89
Revises: b8dc42f28583
Create Date: 2023-07-04 10:52:47.771517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd53a79e9cc89'
down_revision = 'b8dc42f28583'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    org_res = conn.execute(
        'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.create_unique_constraint(None, 'orgs', ['uuid'])
    op.add_column('orgs_version', sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs_version', 'uuid')
    op.drop_constraint(None, 'orgs', type_='unique')
    op.drop_column('orgs', 'uuid')
    # ### end Alembic commands ###
