"""empty message

Revision ID: 0f7e04a673f7
Revises: 4a6eb0fcc93e
Create Date: 2023-09-29 23:30:47.445227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7e04a673f7'
down_revision = '4a6eb0fcc93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliations', sa.Column('environment', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_affiliations_environment'), 'affiliations', ['environment'], unique=False)
    op.add_column('affiliations_version', sa.Column('environment', sa.String(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_affiliations_version_environment'), 'affiliations_version', ['environment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliations_version_environment'), table_name='affiliations_version')
    op.drop_column('affiliations_version', 'environment')
    op.drop_index(op.f('ix_affiliations_environment'), table_name='affiliations')
    op.drop_column('affiliations', 'environment')
    # ### end Alembic commands ###
