"""Add change_adress permission for USER

Revision ID: 3f5b8a19ce42
Revises: aa74003de9d8
Create Date: 2024-11-21 08:19:42.551199

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "3f5b8a19ce42"
down_revision = "aa74003de9d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    op.bulk_insert(
        permissions_table,
        [
            {'membership_type_code': 'USER', 'actions': 'CHANGE_ADDRESS'}
        ]
    )


def downgrade():
    op.execute("delete from permissions where actions='CHANGE_ADDRESS'")
    # ### end Alembic commands ###
