"""empty message

Revision ID: 2080fa3d5945
Revises: bddf9fe7468c
Create Date: 2025-05-14 15:12:33.302354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2080fa3d5945'
down_revision = 'bddf9fe7468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('affiliation_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier_1', sa.String(length=75), nullable=True),
    sa.Column('identifier_2', sa.String(length=75), nullable=True),
    sa.Column('identifier_3', sa.String(length=75), nullable=True),
    sa.Column('business_identifier_affilation_id', sa.Integer(), nullable=True),
    sa.Column('bootstrap_affilation_id', sa.Integer(), nullable=True),
    sa.Column('nr_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bootstrap_affilation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['business_identifier_affilation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nr_affiliation_id'], ['affiliations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_1'),
    sa.UniqueConstraint('identifier_2'),
    sa.UniqueConstraint('identifier_3')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('affiliation_mapping')
    # ### end Alembic commands ###
