"""empty message

Revision ID: 6f2c09061fd3
Revises: bddf9fe7468c
Create Date: 2025-05-22 17:21:47.908470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f2c09061fd3'
down_revision = 'bddf9fe7468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_identifier', sa.String(length=75), nullable=True),
    sa.Column('bootstrap_identifier', sa.String(length=75), nullable=True),
    sa.Column('nr_identifier', sa.String(length=75), nullable=True),
    sa.Column('business_identifier_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('bootstrap_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('nr_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bootstrap_affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['business_identifier_affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nr_affiliation_id'], ['affiliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliation_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliation_mapping_bootstrap_identifier'), ['bootstrap_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliation_mapping_business_identifier'), ['business_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliation_mapping_nr_identifier'), ['nr_identifier'], unique=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation_mapping')
    # ### end Alembic commands ###
