"""Create affiliation_mapping table

Revision ID: 84591539b298
Revises: bddf9fe7468c
Create Date: 2025-05-20 13:35:10.295447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84591539b298'
down_revision = 'bddf9fe7468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_identifier', sa.String(length=75), nullable=True),
    sa.Column('bootstrap_identifier', sa.String(length=75), nullable=True),
    sa.Column('nr_identifier', sa.String(length=75), nullable=True),
    sa.Column('business_identifier_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('bootstrap_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('nr_affiliation_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bootstrap_affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['business_identifier_affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nr_affiliation_id'], ['affiliations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bootstrap_identifier'),
    sa.UniqueConstraint('business_identifier'),
    sa.UniqueConstraint('nr_identifier')
    )
    with op.batch_alter_table('affiliation_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_bootstrap_identifier', ['bootstrap_identifier'], unique=False)
        batch_op.create_index('ix_business_identifier', ['business_identifier'], unique=False)
        batch_op.create_index('ix_nr_identifier', ['nr_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation_mapping')
    # ### end Alembic commands ###
