"""Update the content for termsofuse_govm

Revision ID: beb5b3186f22
Revises: 3f5b8a19ce42
Create Date: 2025-01-30 15:44:51.025774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'beb5b3186f22'
down_revision = '3f5b8a19ce42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    documents = table('documents',
                      column('version_id', String),
                      column('type', String),
                      column('content', String),
                      column('content_type', String),
                      )

    html_content = """
               <article>
               <section>
        <header>Definitions</header>
        <p>In this MOU:</p>
        <p>“Website” means the BC Registry Website at <a href="https://www.bcregistry.gov.bc.ca">https://www.bcregistry.gov.bc.ca</a> and includes all web pages, content, associated materials and the services provided through the Website.</p>
        <p>“Ministry Account” refers to a BC Registry account set up to enable a Ministry or a particular branch or group within a Ministry of the BC government to access the services provided through the Website.</p>
      </section>
      <section>
        <header>Purpose</header>
        <p>This MOU documents the understanding between the Service BC Connect Division of the Ministry of Citizens’ Services (“Service BC Connect”) and the Ministry responsible for the Ministry Account (the “Ministry”) regarding the use of Website.  Service BC Connect and the Ministry are each referred to as a “Party” and together as the “Parties”.  This MOU is not intended to be, nor should it be construed as, a binding agreement.
        </p>
        <p>By clicking the “Accept Terms” button (or any other button or mechanism indicating your acceptance of this MOU) and subscribing to and/or using the Website, the Ministry agrees to the understanding set out in this MOU.  If the Ministry does not agree with the understanding set out in this MOU, the Ministry should not set up a Ministry Account or otherwise use the Website. </p>
      </section>
      <section>
        <header>Ministry Account Usage</header>
        <p>Service BC Connect will set up Ministry Accounts and permit access to Ministry Account users to use the services available on the Website.</p>
        <p>Ministry Accounts will be granted solely for use on behalf of a Ministry or a particular branch or group within a government ministry.  Any use of a Ministry Account to access services for personal purposes is prohibited.  In setting up an account, Ministries must assign an individual to be an administrator of the Ministry account.  Ministry account administrators will designate users for that account and will be required to implement appropriate safeguards to prevent unauthorized use of a Ministry account.  This will include the requirement to remove Ministry Account users when they are no longer employees of that Ministry or the particular branch or group within that Ministry.</p>
      </section>
      <section>
        <header>Online Transactions</header>
        <p>By creating a Ministry Account, a Ministry accepts that any designated Ministry users using the Ministry Account will be performing transactions that have a financial commitment. The Ministry must ensure that Ministry Account users are not making a commitment that would result in greater expense than a ministry’s current year’s appropriation(s) or available funds, and must not continue to complete transactions if there is a known inability to pay for services when due. Ministries are responsible to ensure that Ministry Account users are aware of their financial responsibilities, as outlined in Core Policy and Procedures, Chapter 7: Revenue and Receivables Management <a href="https://www2.gov.bc.ca/gov/content/governments/policies-for-government/core-policy/policies/revenue-and-receivables-management">https://www2.gov.bc.ca/gov/content/governments/policies-for-government/core-policy/policies/revenue-and-receivables-management</a>
          </p><p>Ministries agree to pay service fees, and statutory fees where applicable, as listed on the Website for any transactions and services ordered under Ministry Accounts and payment will be processed through journal voucher.  All fees listed on the Website are in Canadian dollars and charges will be processed in Canadian dollars.  Ministries are responsible to ensure that general ledger information provided for the Ministry Account is accurate and up to date.</p>
        <p>By law, some transactions in Service BC Connect cannot be reversed. For these types of transactions, no refund or credit can be issued.</p>
        </section>
      <section>
        <header>Term</header>
        <p>This MOU continues until the earlier of the following events:
          <ul class="alpha-listing">
            <li>the Province ceases to be the “operator” of BC OnLine within the meaning of the BC OnLine Act; or</li>
            <li>this MOU is terminated by either Party according to this section.</li>
          </ul>
        </p>
        <p>Either Party may terminate this MOU for any reason upon 90 days prior written notice to the other Party.  Upon termination of this MOU, the Ministry is responsible for payment of any outstanding fees for transactions authorized under the Ministry account to the point at which the MOU is terminated.</p>
      </section>
      <section>
        <header>Third Party Links</header>
        <p>The Website may contain links to other websites. Links are provided only as a convenience and the inclusion of any link on the Website does not imply any warranty, endorsement, investigation or verification by Service BC Connect.  If ministries use the linked sites, they should be aware that they may be subject to separate terms and conditions of these websites.</p>
      </section>
      <section>
        <header>Website Content</header>
        <p>Although reasonable efforts are made to ensure that the Website will be current and will contain no errors, omissions, or inaccuracies Service BC Connect cannot guarantee that the operation of the Website or the information, content, or materials included in the Website will be error free or completely accurate or current at all time, or at any time.  Service BC Connect may correct errors or inaccuracies and change or update information on the Website, including price and availability of services, at any time without notice.</p>
      </section>
      <section>
        <header>Data Integrity</header>
        <p>If the Ministry provides data to Service BC Connect to facilitate a transaction on the Website, Ministry Account users must employ reasonable and appropriate efforts to ensure that all such data is accurate.</p>
        <p>When receiving information from the Website, Ministry Account users must use reasonable and appropriate efforts to assure that such information is not altered or corrupted.</p>
      </section>
      <section>
        <header>Changes to MOU</header>
        <p>Service BC Connect reserves the right to modify this MOU at any time at its sole discretion by posting a revised MOU on the Website for acceptance by the Ministry.  Should the Ministry refuse to accept the revised MOU, that Ministry account will no longer have access to the services provided through the Website and the Ministry will be responsible for payment of any Fees incurred by that Ministry Account to that point in time.</p>
      </section>
      <section>
        <header>Suspension</header>
       <p>The Ministry acknowledges that Service BC Connect reserves the right for any reason at any time to limit or suspend access to the Website.</p>
      </section>
      <section>
        <header>Dispute Resolution</header>
        <p>In the event of any dispute in relation to this MOU:
          <ul class="alpha-listing">
            <li>the Parties will attempt to resolve the dispute through the Ministry account administrator and a representative of Service BC Connect;</li>
            <li>if the matter is not resolved by the Parties’ representatives, the parties will refer the matter to their respective senior representatives, as appropriate, up to their respective assistant deputy ministers, or equivalent; and</li>
            <li>if the matter remains unresolved, the Parties will refer the matter to their respective deputy ministers, or equivalent, for resolution.</li>
          </ul>
        </p>
      </section>
             </article>
             """

    op.execute(
        documents.update()
            .where(documents.c.version_id == op.inline_literal('s1') and documents.c.type == 'termsofuse_govm')
            .values({'content': op.inline_literal(html_content)})
    )

    # ### end Alembic commands ###


def downgrade():
    documents = table('documents',
                      column('version_id', String),
                      column('type', String),
                      column('content', String),
                      column('content_type', String),
                      )

    html_content = """
               <article>
               <section>
        <header>Definitions</header>
        <p>In this MOU:</p>
        <p>“Website” means the BC Registry Website at <a href="https://www.bcregistry.gov.bc.ca">https://www.bcregistry.gov.bc.ca</a> and includes all web pages, content, associated materials and the services provided through the Website.</p>
        <p>“Ministry Account” refers to a BC Registry account set up to enable a Ministry or a particular branch or group within a Ministry of the BC government to access the services provided through the Website.</p>
      </section>
      <section>
        <header>Purpose</header>
        <p>This MOU documents the understanding between the BC Registries and Online Services Division of the Ministry of Citizens’ Services (“BC Registries”) and the Ministry responsible for the Ministry Account (the “Ministry”) regarding the use of Website.  BC Registries and the Ministry are each referred to as a “Party” and together as the “Parties”.  This MOU is not intended to be, nor should it be construed as, a binding agreement.
        </p>
        <p>By clicking the “Accept Terms” button (or any other button or mechanism indicating your acceptance of this MOU) and subscribing to and/or using the Website, the Ministry agrees to the understanding set out in this MOU.  If the Ministry does not agree with the understanding set out in this MOU, the Ministry should not set up a Ministry Account or otherwise use the Website. </p>
      </section>
      <section>
        <header>Ministry Account Usage</header>
        <p>BC Registries will set up Ministry Accounts and permit access to Ministry Account users to use the services available on the Website.</p>
        <p>Ministry Accounts will be granted solely for use on behalf of a Ministry or a particular branch or group within a government ministry.  Any use of a Ministry Account to access services for personal purposes is prohibited.  In setting up an account, Ministries must assign an individual to be an administrator of the Ministry account.  Ministry account administrators will designate users for that account and will be required to implement appropriate safeguards to prevent unauthorized use of a Ministry account.  This will include the requirement to remove Ministry Account users when they are no longer employees of that Ministry or the particular branch or group within that Ministry.</p>
      </section>
      <section>
        <header>Online Transactions</header>
        <p>By creating a Ministry Account, a Ministry accepts that any designated Ministry users using the Ministry Account will be performing transactions that have a financial commitment. The Ministry must ensure that Ministry Account users are not making a commitment that would result in greater expense than a ministry’s current year’s appropriation(s) or available funds, and must not continue to complete transactions if there is a known inability to pay for services when due. Ministries are responsible to ensure that Ministry Account users are aware of their financial responsibilities, as outlined in Core Policy and Procedures, Chapter 7: Revenue and Receivables Management <a href="https://www2.gov.bc.ca/gov/content/governments/policies-for-government/core-policy/policies/revenue-and-receivables-management">https://www2.gov.bc.ca/gov/content/governments/policies-for-government/core-policy/policies/revenue-and-receivables-management</a>
          </p><p>Ministries agree to pay service fees, and statutory fees where applicable, as listed on the Website for any transactions and services ordered under Ministry Accounts and payment will be processed through journal voucher.  All fees listed on the Website are in Canadian dollars and charges will be processed in Canadian dollars.  Ministries are responsible to ensure that general ledger information provided for the Ministry Account is accurate and up to date.</p>
        <p>By law, some transactions in BC Registries cannot be reversed. For these types of transactions, no refund or credit can be issued.</p>
        </section>
      <section>
        <header>Term</header>
        <p>This MOU continues until the earlier of the following events:
          <ul class="alpha-listing">
            <li>the Province ceases to be the “operator” of BC OnLine within the meaning of the BC OnLine Act; or</li>
            <li>this MOU is terminated by either Party according to this section.</li>
          </ul>
        </p>
        <p>Either Party may terminate this MOU for any reason upon 90 days prior written notice to the other Party.  Upon termination of this MOU, the Ministry is responsible for payment of any outstanding fees for transactions authorized under the Ministry account to the point at which the MOU is terminated.</p>
      </section>
      <section>
        <header>Third Party Links</header>
        <p>The Website may contain links to other websites. Links are provided only as a convenience and the inclusion of any link on the Website does not imply any warranty, endorsement, investigation or verification by BC Registries.  If ministries use the linked sites, they should be aware that they may be subject to separate terms and conditions of these websites.</p>
      </section>
      <section>
        <header>Website Content</header>
        <p>Although reasonable efforts are made to ensure that the Website will be current and will contain no errors, omissions, or inaccuracies BC Registries cannot guarantee that the operation of the Website or the information, content, or materials included in the Website will be error free or completely accurate or current at all time, or at any time.  BC Registries may correct errors or inaccuracies and change or update information on the Website, including price and availability of services, at any time without notice.</p>
      </section>
      <section>
        <header>Data Integrity</header>
        <p>If the Ministry provides data to BC Registries to facilitate a transaction on the Website, Ministry Account users must employ reasonable and appropriate efforts to ensure that all such data is accurate.</p>
        <p>When receiving information from the Website, Ministry Account users must use reasonable and appropriate efforts to assure that such information is not altered or corrupted.</p>
      </section>
      <section>
        <header>Changes to MOU</header>
        <p>BC Registries reserves the right to modify this MOU at any time at its sole discretion by posting a revised MOU on the Website for acceptance by the Ministry.  Should the Ministry refuse to accept the revised MOU, that Ministry account will no longer have access to the services provided through the Website and the Ministry will be responsible for payment of any Fees incurred by that Ministry Account to that point in time.</p>
      </section>
      <section>
        <header>Suspension</header>
       <p>The Ministry acknowledges that BC Registries reserves the right for any reason at any time to limit or suspend access to the Website.</p>
      </section>
      <section>
        <header>Dispute Resolution</header>
        <p>In the event of any dispute in relation to this MOU:
          <ul class="alpha-listing">
            <li>the Parties will attempt to resolve the dispute through the Ministry account administrator and a representative of BC Registries;</li>
            <li>if the matter is not resolved by the Parties’ representatives, the parties will refer the matter to their respective senior representatives, as appropriate, up to their respective assistant deputy ministers, or equivalent; and</li>
            <li>if the matter remains unresolved, the Parties will refer the matter to their respective deputy ministers, or equivalent, for resolution.</li>
          </ul>
        </p>
      </section>
             </article>
             """

    op.execute(
        documents.update()
            .where(documents.c.version_id == op.inline_literal('s1') and documents.c.type == 'termsofuse_govm')
            .values({'content': op.inline_literal(html_content)})
    )