"""remove_billable

Revision ID: 2468d14cc44c
Revises: 37dc988611c6
Create Date: 2021-09-27 14:51:16.980546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2468d14cc44c'
down_revision = '37dc988611c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs', 'billable')
    op.drop_column('orgs_version', 'billable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs_version', sa.Column('billable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orgs', sa.Column('billable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
