"""added tos for idir

Revision ID: 2eb11ab005d3
Revises: e777dd2575e2
Create Date: 2021-05-06 15:27:24.864170

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table
from sqlalchemy import Integer, String

# revision identifiers, used by Alembic.
revision = '2eb11ab005d3'
down_revision = 'e777dd2575e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    documents = table('documents',
                      column('version_id', String),
                      column('type', String),
                      column('content', String),
                      column('content_type', String),
                      )

    html_content = """
           <article>
           <p>The parties to this “BC Registry Terms and Conditions of Agreement” (the “Agreement”) are Her Majesty the Queen in Right of the Province of British Columbia, as represented by the Minister of Citizens’ Services (the “Province”) and the Subscriber (as defined below).</p>

           <section>
        <p>In this Ministry Use Agreement “Website” means the BC Registry Website at <a hre="https://www.bcregistry.ca/business/auth/home/decide-business">https://www.bcregistry.ca/business/auth/home/decide-business</a> and includes all web pages and associated materials.</p>
        <p>The Ministry Use Agreement, and Terms and Conditions available through the website, herein govern the use of this website, its content, and the services provided through the website (collectively the “BC Registry Website”). Each time you use the BC Registry Website, you signify your acknowledgement and acceptance of the Ministry Use Agreement below and Terms and Conditions available through the Website.</p>
        <p>Ministry Account refers to all BC Registry accounts set up for Provincial Government Ministry Partners.</p>
      </section>
      <section>
        <header>Online Transactions</header>
        <p>By creating a Ministry Account, a Ministry has accepted that the Subscriber or Team Member will be performing transactions that have a financial commitment. The Ministry must ensure that Ministry Account holders are not making a commitment that would result in greater expense than a ministry’s current year’s appropriation(s) or available funds. Ministry Account holders should be aware of their financial responsibilities, as outlined in Core Policy and Procedures, Chapter 7: Revenue and Receivables Management https://www2.gov.bc.ca/gov/content/governments/policies-for-government/core-policy/policies/revenue-and-receivables-management
        </p>
        <p>Transactions and Services completed under Ministry Accounts will result in fee recovery. Ministries are responsible for service fees, and statutory fees where applicable. Ministry accounts shall not continue to complete transactions if there is a known inability to pay for services when due.</p>
        <p>All prices listed on the BC Registry Website are in Canadian dollars and charges will be processed in Canadian dollars.</p>
        <p>By law, some transactions in BC Registries cannot be reversed. For these types of transactions, no refund or credit can be issued.</p>
      </section>
      <section>
        <header>Ministry Account Usage</header>
        <p>Ministry account are granted solely for use on behalf of a government ministry. Accessing services through a ministry account for personal purposes is prohibited. Ministry account administrators are required to implement appropriate safeguards to prevent unauthorized use of a ministry account. This includes the requirement to remove team members who are no longer employees of their ministry in the Province of BC. </p>
      </section>
      <section>
        <header>Third Party Links</header>
        <p>The BC Registry Website may contain links to other websites. BC Registries and Online Services provides links to you only as a convenience and the inclusion of any link on this website does not imply any warranty, endorsement, investigation or verification by BC Registries and Online Services. Your use of the linked sites may be subject to terms and conditions in these websites, which you should locate and review. BC Registries and Online Services has no control over and expressly disclaims any liability for these websites or their content.
</p>
        </section>
        <section>
        <header>Website Content </header>
        <p>BC Registries and Online Services makes no representation or warranties whatsoever, either expressed or implied, with respect to the accuracy of the information obtained through the BC Registry Website. This website is provided "as is" and shall be used by you at your own risk. Although reasonable efforts are made to ensure that this website will be current and will contain no errors, omissions, or inaccuracies, no representations, warranties, guarantees, or conditions (either expressed or implied) are given as to the operation of this website or that this website and the information, content, or materials included in this website will be error free or completely accurate or current at all time, or at any time. BC Registries and Online Services may correct errors or inaccuracies and change or update information on this site at any time without notice including price and availability</p>
        </section>
        <section>
        <header>Disclaimer and Limitation of Liability </header>
        <p>The BC Registry Website is provided on an “as is” and “as available” basis, and without any representations, warranties or conditions of any kind, whether express or implied, and including without limitation implied warranties of merchantability, fitness for a particular purpose, performance or durability, all of which are hereby disclaimed by BC Registries and Online Services, and the Province of British Columbia to the fullest extent permitted by law. BC Registries and Online Services, the Province of British Columbia, and its respective directors, employees and other representatives will not under any circumstances be liable for damages arising out of or in connection with the use of the BC Registry Website, or any hyperlinked website, whether or not such damages might be foreseeable and even if BC Registry is informed of their possibility. This is a comprehensive limitation of liability that applies to all damages of any kind, including (without limitation) compensatory, direct, indirect, or consequential damages, loss of data, income or profit, loss of or damage to property and claims of third parties.</p>
      </section>
      <section>
        <header>Data Quality</header>
       <p>Ministry account users shall employ reasonable and appropriate efforts to ensure that all data provided through transactions is accurate. Ministry account administrators shall use reasonable and appropriate efforts to assure that personnel do not alter, or corrupt data received or transmitted.</p>
      </section>
      <section>
        <header>Changes</header>
        <p>The information contained in this website is subject to change and update at any time without prior notice. BC Registries and Online Services reserves the right to modify this Ministry Use Agreement at any time at its sole discretion by issuing a revised Ministry Use Agreement, and you agree to comply with and be bound by such.a</p>
      </section>
    <section>
      <header>Miscellaneous </header>
      <p>Any failure to insist upon or enforce strict performance on any provision of the Ministry Use Agreement shall not be construed as a waiver of any right. If any part of this notice is determined to be void, invalid or otherwise unenforceable by a court of competent jurisdiction, such determination shall not affect the remaining provisions hereof.       </p>
    </section>

         </article>
         """

    op.bulk_insert(
        documents,
        [
            {'version_id': 's1', 'type': 'termsofuse_govm', 'content': html_content, 'content_type': 'text/html'}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM DOCUMENTS WHERE version_id='s1' AND type='termsofuse_govm'")
