"""Add type_code to products

Revision ID: 3013ef68d7f1
Revises: 09c44f82c03c
Create Date: 2020-03-27 15:16:37.176814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3013ef68d7f1'
down_revision = '09c44f82c03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    product_type_code_table = op.create_table('product_type_code',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )

    op.bulk_insert(
        product_type_code_table,
        [
            {'code': 'INTERNAL', 'desc': 'BC Registries Online internal product', 'default': True},
            {'code': 'PARTNER', 'desc': 'A partner application to BC Registries Online', 'default': False}
        ]
    )

    op.add_column('product_code', sa.Column('type_code', sa.String(length=15), nullable=True))
    op.create_foreign_key('product_code_type_code_fkey', 'product_code', 'product_type_code', ['type_code'], ['code'])

    op.execute("UPDATE product_code SET type_code = 'INTERNAL'")

    op.alter_column('product_code', 'type_code', nullable=False)

    product_code_table = sa.sql.table('product_code',
        sa.column('code', sa.String),
        sa.column('desc', sa.String),
        sa.column('default', sa.Boolean),
        sa.column('type_code', sa.String)
    )

    op.bulk_insert(
        product_code_table,
        [
            {'code': 'BUSINESS', 'desc': 'Business Registry', 'default': False, 'type_code': 'INTERNAL'},
            {'code': 'VS', 'desc': 'Vital Statistics', 'default': False, 'type_code': 'PARTNER'},
            {'code': 'BCA', 'desc': 'BC Assessment', 'default': False, 'type_code': 'PARTNER'}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_code_type_code_fkey', 'product_code', type_='foreignkey')
    op.drop_column('product_code', 'type_code')
    op.drop_table('product_type_code')

    op.execute("DELETE FROM product_code WHERE code in ('BUSINESS', 'VS', 'BCA')")
    # ### end Alembic commands ###
