"""Update org table

Revision ID: 34072bd34e91
Revises: e5647206acf5
Create Date: 2019-08-12 11:41:14.217010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34072bd34e91'
down_revision = 'e5647206acf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('org', sa.Column('last_modified_by_id', sa.Integer(), nullable=False))
    op.add_column('org', sa.Column('preferred_payment_code', sa.String(length=15), nullable=False))
    op.drop_constraint('org_last_modified_by_fkey', 'org', type_='foreignkey')
    op.drop_constraint('org_contact2_fkey', 'org', type_='foreignkey')
    op.drop_constraint('org_contact1_fkey', 'org', type_='foreignkey')
    op.drop_constraint('org_created_by_fkey', 'org', type_='foreignkey')
    op.drop_constraint('org_preferred_payment_fkey', 'org', type_='foreignkey')
    op.create_foreign_key(None, 'org', 'payment_type', ['preferred_payment_code'], ['code'])
    op.create_foreign_key(None, 'org', 'user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key(None, 'org', 'user', ['created_by_id'], ['id'])
    op.drop_column('org', 'last_modified_by')
    op.drop_column('org', 'contact2')
    op.drop_column('org', 'contact1')
    op.drop_column('org', 'created_by')
    op.drop_column('org', 'preferred_payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('preferred_payment', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('contact1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('org', sa.Column('contact2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('org', sa.Column('last_modified_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'org', type_='foreignkey')
    op.drop_constraint(None, 'org', type_='foreignkey')
    op.drop_constraint(None, 'org', type_='foreignkey')
    op.create_foreign_key('org_preferred_payment_fkey', 'org', 'payment_type', ['preferred_payment'], ['code'])
    op.create_foreign_key('org_created_by_fkey', 'org', 'user', ['created_by'], ['id'])
    op.create_foreign_key('org_contact1_fkey', 'org', 'contact', ['contact1'], ['id'])
    op.create_foreign_key('org_contact2_fkey', 'org', 'contact', ['contact2'], ['id'])
    op.create_foreign_key('org_last_modified_by_fkey', 'org', 'user', ['last_modified_by'], ['id'])
    op.drop_column('org', 'preferred_payment_code')
    op.drop_column('org', 'last_modified_by_id')
    op.drop_column('org', 'created_by_id')
    # ### end Alembic commands ###
