"""Initialization MVP

Revision ID: 414773385d34
Revises: 
Create Date: 2019-08-15 11:30:44.157239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '414773385d34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_identifier', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_identifier')
    )
    op.create_table('membership_type',
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('org_status',
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('org_type',
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_type',
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('keycloak_guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('roles', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keycloak_guid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=250), nullable=True),
    sa.Column('street_additional', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=4096), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('phone_extension', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_street'), 'contact', ['street'], unique=False)
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=15), nullable=False),
    sa.Column('status_code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('contact1', sa.Integer(), nullable=True),
    sa.Column('contact2', sa.Integer(), nullable=True),
    sa.Column('preferred_payment', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['contact1'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['contact2'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['preferred_payment'], ['payment_type.code'], ),
    sa.ForeignKeyConstraint(['status_code'], ['org_status.code'], ),
    sa.ForeignKeyConstraint(['type_code'], ['org_type.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_name'), 'org', ['name'], unique=False)
    op.create_table('affiliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.Integer(), nullable=False),
    sa.Column('org', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entity'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['org'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('org', sa.Integer(), nullable=False),
    sa.Column('membership_type', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['membership_type'], ['membership_type.code'], ),
    sa.ForeignKeyConstraint(['org'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_table('affiliation')
    op.drop_index(op.f('ix_org_name'), table_name='org')
    op.drop_table('org')
    op.drop_index(op.f('ix_contact_street'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('payment_type')
    op.drop_table('org_type')
    op.drop_table('org_status')
    op.drop_table('membership_type')
    op.drop_table('entity')
    # ### end Alembic commands ###
