"""entity_changes

Revision ID: 41ac4080a7ed
Revises: eb771b2012b7
Create Date: 2021-08-04 11:16:18.636341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '41ac4080a7ed'
down_revision = 'eb771b2012b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('last_modified_by', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'status')
    op.drop_column('entities', 'last_modified_by')
    op.drop_column('entities', 'last_modified')
    # ### end Alembic commands ###
