"""user_remove_roles

Revision ID: 4c6ca48245be
Revises: d5b5eb2e8dd0
Create Date: 2021-03-08 11:37:13.600415

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "4c6ca48245be"
down_revision = "d5b5eb2e8dd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update users set type='ANONYMOUS_USER' where type='ANONYMOUS'")
    conn = op.get_bind()
    res = conn.execute(text("select id, type, login_source, username, roles from users where type is null"))
    users = res.fetchall()

    for user in users:
        id = user[0]
        username = user[3]
        if any(username in s for s in ["@idir", "idir\\", "idir@"]):
            op.execute(f"update users set type='STAFF' where id={id}")
        elif any(username in s for s in ["@bcsc", "bcsc\\", "bcsc@", "@bceid", "bceid\\", "bceid@"]):
            op.execute(f"update users set type='PUBLIC_USER' where id={id}")

    op.drop_column("users", "roles")
    op.drop_column("users_version", "roles")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_version", sa.Column("roles", sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("roles", sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
