"""added suspension reason codes

Revision ID: 5053985bdfc6
Revises: 8260fac9943d
Create Date: 2021-02-28 13:47:45.817262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5053985bdfc6'
down_revision = '8260fac9943d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    suspension_reason_codes = op.create_table('suspension_reason_codes',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('orgs', sa.Column('suspension_reason_code', sa.String(length=15), nullable=True))
    op.create_foreign_key('orgs_suspension_reason_code_fkey', 'orgs', 'suspension_reason_codes', ['suspension_reason_code'], ['code'], ondelete='SET NULL')
    op.add_column('orgs_version', sa.Column('suspension_reason_code', sa.String(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    # Insert code values
    op.bulk_insert(
        suspension_reason_codes,
        [
            {'code': 'OWNER_CHANGE', 'description': 'Account Ownership Change', 'default': True},
            {'code': 'DISPUTE', 'description': 'Account Ownership Dispute', 'default': False},
            {'code': 'COURT_ORDER', 'description': 'Court Order', 'default': False},
            {'code': 'FRAUDULENT', 'description': 'Fraudulent Activity', 'default': False}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs_version', 'suspension_reason_code')
    op.drop_constraint('orgs_suspension_reason_code_fkey', 'orgs', type_='foreignkey')
    op.drop_column('orgs', 'suspension_reason_code')
    op.drop_table('suspension_reason_codes')
    # ### end Alembic commands ###
