"""added reset password permission

Revision ID: 598dd27fc660
Revises: d34f68927bdf
Create Date: 2020-05-31 06:52:08.190916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table



# revision identifiers, used by Alembic.
revision = '598dd27fc660'
down_revision = 'd34f68927bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {'id': '12', 'membership_type_code': 'ADMIN', 'actions': 'RESET_PASSWORD'},
        ]
    )


def downgrade():
    op.execute('delete from permissions where id=12')
