"""Update base model

Revision ID: 6ae6bd8d5033
Revises: 34072bd34e91
Create Date: 2019-08-13 14:00:30.845826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ae6bd8d5033'
down_revision = '34072bd34e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('affiliation', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('affiliation', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('affiliation_created_by_fkey', 'affiliation', type_='foreignkey')
    op.create_foreign_key(None, 'affiliation', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'affiliation', 'user', ['modified_by_id'], ['id'])
    op.drop_column('affiliation', 'created_by')
    op.add_column('contact', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('contact', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'contact', 'user', ['modified_by_id'], ['id'])
    op.add_column('contact_link', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('contact_link', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('contact_link', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('contact_link', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact_link', 'user', ['modified_by_id'], ['id'])
    op.create_foreign_key(None, 'contact_link', 'user', ['created_by_id'], ['id'])
    op.add_column('entity', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('entity', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('entity', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('entity', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entity', 'user', ['modified_by_id'], ['id'])
    op.create_foreign_key(None, 'entity', 'user', ['created_by_id'], ['id'])
    op.add_column('membership', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('membership', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('membership', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'membership', 'user', ['modified_by_id'], ['id'])
    op.create_foreign_key(None, 'membership', 'user', ['created_by_id'], ['id'])
    op.add_column('membership_type', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('membership_type', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('membership_type', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('membership_type', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'membership_type', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'membership_type', 'user', ['modified_by_id'], ['id'])
    op.add_column('org', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('org', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.alter_column('org', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('org_last_modified_by_id_fkey', 'org', type_='foreignkey')
    op.create_foreign_key(None, 'org', 'user', ['modified_by_id'], ['id'])
    op.drop_column('org', 'last_modified_by_id')
    op.drop_column('org', 'last_modified')
    op.add_column('org_status', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('org_status', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('org_status', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('org_status', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'org_status', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'org_status', 'user', ['modified_by_id'], ['id'])
    op.add_column('org_type', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('org_type', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('org_type', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('org_type', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'org_type', 'user', ['modified_by_id'], ['id'])
    op.create_foreign_key(None, 'org_type', 'user', ['created_by_id'], ['id'])
    op.add_column('user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['modified_by_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'modified_by_id')
    op.drop_column('user', 'created_by_id')
    op.drop_constraint(None, 'org_type', type_='foreignkey')
    op.drop_constraint(None, 'org_type', type_='foreignkey')
    op.drop_column('org_type', 'modified_by_id')
    op.drop_column('org_type', 'modified')
    op.drop_column('org_type', 'created_by_id')
    op.drop_column('org_type', 'created')
    op.drop_constraint(None, 'org_status', type_='foreignkey')
    op.drop_constraint(None, 'org_status', type_='foreignkey')
    op.drop_column('org_status', 'modified_by_id')
    op.drop_column('org_status', 'modified')
    op.drop_column('org_status', 'created_by_id')
    op.drop_column('org_status', 'created')
    op.add_column('org', sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('org', sa.Column('last_modified_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'org', type_='foreignkey')
    op.create_foreign_key('org_last_modified_by_id_fkey', 'org', 'user', ['last_modified_by_id'], ['id'])
    op.alter_column('org', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('org', 'modified_by_id')
    op.drop_column('org', 'modified')
    op.drop_constraint(None, 'membership_type', type_='foreignkey')
    op.drop_constraint(None, 'membership_type', type_='foreignkey')
    op.drop_column('membership_type', 'modified_by_id')
    op.drop_column('membership_type', 'modified')
    op.drop_column('membership_type', 'created_by_id')
    op.drop_column('membership_type', 'created')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_column('membership', 'modified_by_id')
    op.drop_column('membership', 'modified')
    op.drop_column('membership', 'created_by_id')
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_column('entity', 'modified_by_id')
    op.drop_column('entity', 'modified')
    op.drop_column('entity', 'created_by_id')
    op.drop_column('entity', 'created')
    op.drop_constraint(None, 'contact_link', type_='foreignkey')
    op.drop_constraint(None, 'contact_link', type_='foreignkey')
    op.drop_column('contact_link', 'modified_by_id')
    op.drop_column('contact_link', 'modified')
    op.drop_column('contact_link', 'created_by_id')
    op.drop_column('contact_link', 'created')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'modified_by_id')
    op.drop_column('contact', 'modified')
    op.drop_column('contact', 'created_by_id')
    op.drop_column('contact', 'created')
    op.add_column('affiliation', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'affiliation', type_='foreignkey')
    op.drop_constraint(None, 'affiliation', type_='foreignkey')
    op.create_foreign_key('affiliation_created_by_fkey', 'affiliation', 'user', ['created_by'], ['id'])
    op.drop_column('affiliation', 'modified_by_id')
    op.drop_column('affiliation', 'modified')
    op.drop_column('affiliation', 'created_by_id')
    # ### end Alembic commands ###
