"""add membership status

Revision ID: 73d70e9f56b5
Revises: d0cd84858921
Create Date: 2019-11-09 05:56:04.337793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d70e9f56b5'
down_revision = 'd0cd84858921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    membership_status_code = op.create_table('membership_status_code',
                                             sa.Column('created', sa.DateTime(), nullable=True),
                                             sa.Column('modified', sa.DateTime(), nullable=True),
                                             sa.Column('id', sa.Integer(), nullable=False),
                                             sa.Column('name', sa.String(length=25), nullable=True),
                                             sa.Column('description', sa.String(length=100), nullable=True),
                                             sa.Column('created_by_id', sa.Integer(), nullable=True),
                                             sa.Column('modified_by_id', sa.Integer(), nullable=True),
                                             sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
                                             sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
                                             sa.PrimaryKeyConstraint('id')
                                             )
    op.add_column('membership', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_membership_status_code', 'membership', 'membership_status_code', ['status'], ['id'])

    op.bulk_insert(
        membership_status_code,
        [
            {'id': '1', 'name': 'ACTIVE', 'description': 'Active Users ;Active in the system'},
            {'id': '2', 'name': 'INACTIVE', 'description': 'Inactive Users;Not fetched anywhere'},
            {'id': '3', 'name': 'REJECTED', 'description': 'Rejected'},
            {'id': '4', 'name': 'PENDING_APPROVAL', 'description': 'Pending Admin Approval'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_membership_status_code', 'membership', type_='foreignkey')
    op.drop_column('membership', 'status')
    op.drop_table('membership_status_code')
    # ### end Alembic commands ###
