"""org type added to permission 

Revision ID: 75336ba7d252
Revises: fc8b221f938f
Create Date: 2020-11-24 06:17:51.309701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = '75336ba7d252'
down_revision = 'fc8b221f938f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('org_status_code', sa.String(length=25), nullable=True))
    op.alter_column('permissions', 'membership_type_code',
                    existing_type=sa.VARCHAR(length=15),
                    type_=sa.String(length=25),
                    nullable=True)
    op.drop_constraint('permissions_membership_type_code_fkey', 'permissions', type_='foreignkey')

    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('org_status_code', sa.String(length=25)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    c = 25
    op.bulk_insert(
        permissions_table,
        [
            {'id': 25, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'MANAGE_STATEMENTS'},
            {'id': 26, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'VIEW_ACCOUNT'},
            {'id': 27, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'INVITE_MEMBERS'},
            {'id': 28, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},

            {'id': 29, 'membership_type_code': 'ADMIN', 'org_status_code': None,
             'actions': 'edit'},
            {'id': 30, 'membership_type_code': 'ADMIN', 'org_status_code': None,
             'actions': 'view'},
            {'id': 31, 'membership_type_code': 'ADMIN', 'org_status_code': None,
             'actions': 'make-payment'},
            {'id': 32, 'membership_type_code': 'ADMIN', 'org_status_code': None,
             'actions': 'generate-invoice'},

            {'id': 33, 'membership_type_code': 'COORDINATOR', 'org_status_code': None,
             'actions': 'edit'},
            {'id': 34, 'membership_type_code': 'COORDINATOR', 'org_status_code': None,
             'actions': 'view'},
            {'id': 35, 'membership_type_code': 'COORDINATOR', 'org_status_code': None,
             'actions': 'make-payment'},
            {'id': 36, 'membership_type_code': 'COORDINATOR', 'org_status_code': None,
             'actions': 'generate-invoice'},

            {'id': 37, 'membership_type_code': 'USER', 'org_status_code': None,
             'actions': 'edit'},
            {'id': 38, 'membership_type_code': 'USER', 'org_status_code': None,
             'actions': 'view'},
            {'id': 39, 'membership_type_code': 'USER', 'org_status_code': None,
             'actions': 'make-payment'},
            {'id': 40, 'membership_type_code': 'USER', 'org_status_code': None,
             'actions': 'generate-invoice'},

            {'id': 41, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},
            {'id': 42, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},
            {'id': 43, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},
            {'id': 44, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},
            {'id': 45, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},
            {'id': 46, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'TRANSACTION_HISTORY'},

            {'id': 47, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'make-payment'},
            {'id': 48, 'membership_type_code': 'ADMIN', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'generate-invoice'},

            {'id': 49, 'membership_type_code': 'SYSTEM', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'make-payment'},
            {'id': 50, 'membership_type_code': 'SYSTEM', 'org_status_code': 'NSF_SUSPENDED',
             'actions': 'generate-invoice'},

            {'id': 51, 'membership_type_code': 'SYSTEM', 'org_status_code': None,
             'actions': 'make-payment'},
            {'id': 52, 'membership_type_code': 'SYSTEM', 'org_status_code': None,
             'actions': 'generate-invoice'},
            {'id': 53, 'membership_type_code': 'SYSTEM', 'org_status_code': None,
             'actions': 'view'},
            {'id': 54, 'membership_type_code': 'SYSTEM', 'org_status_code': None,
             'actions': 'edit'},
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from permissions where id between 25 and 54')
    op.create_foreign_key('permissions_membership_type_code_fkey', 'permissions', 'membership_type',
                          ['membership_type_code'], ['code'])
    op.alter_column('permissions', 'membership_type_code',
                    existing_type=sa.String(length=25),
                    type_=sa.VARCHAR(length=15),
                    nullable=False)
    op.drop_column('permissions', 'org_status_code')

    # ### end Alembic commands ###
