"""refactor column names in tasks table

Revision ID: 89b1e9096ad4
Revises: b22ee0cd18ad
Create Date: 2021-04-03 22:52:44.622499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b1e9096ad4'
down_revision = 'b22ee0cd18ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('related_to', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('tasks', sa.Column('type', sa.String(length=50), nullable=False))
    op.create_foreign_key('related_to_fkey', 'tasks', 'users', ['related_to'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'task_status')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('task_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('related_to_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'related_to')
    # ### end Alembic commands ###
