"""product_code_flags

Revision ID: 9b04140db7d3
Revises: c21389f4b51c
Create Date: 2021-05-25 14:13:51.299973

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9b04140db7d3'
down_revision = 'c21389f4b51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_org_id'), 'activity_logs', ['org_id'], unique=False)
    op.add_column('product_codes', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('product_codes', sa.Column('linked_product_code', sa.String(length=100), nullable=True))
    op.add_column('product_codes', sa.Column('need_review', sa.Boolean(), nullable=True))
    op.add_column('product_codes', sa.Column('premium_only', sa.Boolean(), nullable=True))
    op.add_column('product_codes', sa.Column('url', sa.String(length=100), nullable=True))
    op.drop_constraint('product_codes_status_fk', 'product_codes', type_='foreignkey')
    op.drop_column('product_codes', 'default_subscription_status')

    # Update product codes
    op.execute("update product_codes set hidden=false, linked_product_code='NRO', description='Business Registry & Name Request', need_review=false, premium_only=false, url='https://dev.bcregistry.ca/business'  where code='BUSINESS'")
    op.execute(
        "update product_codes set hidden=true, linked_product_code=null, need_review=false, premium_only=false, url='https://www.bcregistry.ca/namerequest'  where code='NRO'")
    op.execute(
        "update product_codes set hidden=false, need_review=false, premium_only=true, url='https://www.bcregistry.ca/ppr'  where code='PPR'")
    op.execute(
        "update product_codes set hidden=true, need_review=true, premium_only=true, url='https://www.bcregistry.ca/directorsearch'  where code='DIR_SEARCH'")
    op.execute(
        "update product_codes set hidden=true, need_review=true, premium_only=true, url=''  where code='BCA'")
    op.execute(
        "update product_codes set hidden=false, need_review=true, premium_only=false, url=''  where code='VS'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_codes', sa.Column('default_subscription_status', sa.VARCHAR(length=30),
                                             server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False,
                                             nullable=False))
    op.create_foreign_key('product_codes_status_fk', 'product_codes', 'product_subscriptions_statuses',
                          ['default_subscription_status'], ['code'])
    op.drop_column('product_codes', 'url')
    op.drop_column('product_codes', 'premium_only')
    op.drop_column('product_codes', 'need_review')
    op.drop_column('product_codes', 'linked_product_code')
    op.drop_column('product_codes', 'hidden')
    op.drop_index(op.f('ix_activity_logs_org_id'), table_name='activity_logs')
    # ### end Alembic commands ###
