"""Updates to affiliation, membership

Revision ID: a4519a2af112
Revises: 4150773f899f
Create Date: 2019-08-23 14:41:22.612487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'a4519a2af112'
down_revision = '4150773f899f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.add_column('affiliation', sa.Column('org_id', sa.Integer(), nullable=False))
    op.drop_constraint('affiliation_org_fkey', 'affiliation', type_='foreignkey')
    op.drop_constraint('affiliation_entity_fkey', 'affiliation', type_='foreignkey')
    op.create_foreign_key(None, 'affiliation', 'org', ['org_id'], ['id'])
    op.create_foreign_key(None, 'affiliation', 'entity', ['entity_id'], ['id'])
    op.drop_column('affiliation', 'org')
    op.drop_column('affiliation', 'entity')
    op.add_column('membership', sa.Column('membership_type_code', sa.String(length=15), nullable=False))
    op.add_column('membership', sa.Column('org_id', sa.Integer(), nullable=False))
    op.add_column('membership', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('membership_membership_type_fkey', 'membership', type_='foreignkey')
    op.drop_constraint('membership_org_fkey', 'membership', type_='foreignkey')
    op.drop_constraint('membership_user_fkey', 'membership', type_='foreignkey')
    op.create_foreign_key(None, 'membership', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'membership', 'membership_type', ['membership_type_code'], ['code'])
    op.create_foreign_key(None, 'membership', 'org', ['org_id'], ['id'])
    op.drop_column('membership', 'membership_type')
    op.drop_column('membership', 'org')
    op.drop_column('membership', 'user')
    op.add_column('membership_type', sa.Column('default', sa.Boolean(), nullable=False))

    membership_type_table = table('membership_type',
                                    column('code', String),
                                    column('desc', String),
                                    column('default', Boolean)
                                    )

    op.bulk_insert(
        membership_type_table,
        [
            {'code': 'OWNER', 'desc': 'Owner (super-admin) of the organization', 'default': False},
            {'code': 'ADMIN', 'desc': 'Admin for the organization', 'default': False},
            {'code': 'MEMBER', 'desc': 'Member of the organization', 'default': True}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE membership_type CASCADE;')
    op.execute('TRUNCATE TABLE membership CASCADE;')
    op.execute('TRUNCATE TABLE affiliation CASCADE;')

    op.drop_column('membership_type', 'default')
    op.add_column('membership', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('membership', sa.Column('org', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('membership', sa.Column('membership_type', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.create_foreign_key('membership_user_fkey', 'membership', 'user', ['user'], ['id'])
    op.create_foreign_key('membership_org_fkey', 'membership', 'org', ['org'], ['id'])
    op.create_foreign_key('membership_membership_type_fkey', 'membership', 'membership_type', ['membership_type'], ['code'])
    op.drop_column('membership', 'user_id')
    op.drop_column('membership', 'org_id')
    op.drop_column('membership', 'membership_type_code')
    op.add_column('affiliation', sa.Column('entity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('affiliation', sa.Column('org', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('affiliation_entity_fkey', 'affiliation', 'entity', ['entity'], ['id'])
    op.create_foreign_key('affiliation_org_fkey', 'affiliation', 'org', ['org'], ['id'])
    op.drop_column('affiliation', 'org_id')
    op.drop_column('affiliation', 'entity_id')
    # ### end Alembic commands ###
