"""added user type

Revision ID: abc8cc7b64e1
Revises: 9b3cd480fa3b
Create Date: 2020-03-13 13:03:26.529874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc8cc7b64e1'
down_revision = '9b3cd480fa3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('user', sa.Column('type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
