"""1332_removing_non_null_constraints_on_entity

Revision ID: b2749f31f268
Revises: 4a305e1c8c69
Create Date: 2019-09-24 14:48:54.760496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2749f31f268'
down_revision = '4a305e1c8c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'business_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('entity', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('entity', 'business_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
