"""Update org_type and org_status

Revision ID: b2dda0178918
Revises: 2bbce85a5141
Create Date: 2019-08-14 11:42:56.133010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dda0178918'
down_revision = '2bbce85a5141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_status', sa.Column('default', sa.Boolean(), nullable=False))
    op.add_column('org_type', sa.Column('default', sa.Boolean(), nullable=False))
    op.add_column('payment_type', sa.Column('default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_type', 'default')
    op.drop_column('org_status', 'default')
    op.drop_column('payment_type', 'default')
    # ### end Alembic commands ###
