"""add tos verion 4

Revision ID: c10f494d7e10
Revises: aaa29018c0a1
Create Date: 2020-12-24 11:04:39.997395

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table
from sqlalchemy import Integer, String


# revision identifiers, used by Alembic.
revision = 'c10f494d7e10'
down_revision = 'aaa29018c0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    documents = table('documents',
                      column('version_id', String),
                      column('type', String),
                      column('content_type', String),
                      column('content', String))

    html_content = """
       # Put new TOS HTML content here.
     """

    op.bulk_insert(
        documents,
        [
            {'version_id': '4', 'type': 'termsofuse', 'content': html_content, 'content_type': 'text/html'}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM DOCUMENTS WHERE version_id='4' AND type='termsofuse'")
    # ### end Alembic commands ###
