"""permission for account settings and reports

Revision ID: c142314f322b
Revises: 4d115fc3642c
Create Date: 2020-07-15 12:46:01.485455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'c142314f322b'
down_revision = '4d115fc3642c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {'id': '14', 'membership_type_code': 'ADMIN', 'actions': 'SET_AUTH_OPTIONS'},
            {'id': '15', 'membership_type_code': 'ADMIN', 'actions': 'TRANSACTION_HISTORY'},
            {'id': '16', 'membership_type_code': 'COORDINATOR', 'actions': 'TRANSACTION_HISTORY'}
        ]
    )


def downgrade():
    op.execute('delete from permissions where id=14')
    op.execute('delete from permissions where id=15')
    op.execute('delete from permissions where id=16')
