"""token column to invitation table

Revision ID: c1ad99c1898e
Revises: d59e32d1f78b
Create Date: 2019-12-30 22:04:52.311646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ad99c1898e'
down_revision = 'd59e32d1f78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'token')
    # ### end Alembic commands ###
