"""Revert indexes - no use.

Revision ID: c6e4754d28cf
Revises: 80d7590875fa
Create Date: 2022-07-25 08:15:13.510185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e4754d28cf'
down_revision = '80d7590875fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_links_affidavit_id', table_name='contact_links')
    op.drop_index('ix_contact_links_version_affidavit_id', table_name='contact_links_version')
    op.drop_index('ix_contacts_entity_id', table_name='contacts')
    op.drop_index('ix_contacts_version_entity_id', table_name='contacts_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_version_entity_id', 'contacts_version', ['entity_id'], unique=False)
    op.create_index('ix_contacts_entity_id', 'contacts', ['entity_id'], unique=False)
    op.create_index('ix_contact_links_version_affidavit_id', 'contact_links_version', ['affidavit_id'], unique=False)
    op.create_index('ix_contact_links_affidavit_id', 'contact_links', ['affidavit_id'], unique=False)
    # ### end Alembic commands ###
