"""product_auth_changes

Revision ID: cadc28cb38d3
Revises: c1ad99c1898e
Create Date: 2020-02-04 12:44:05.155799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Integer, Boolean
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'cadc28cb38d3'
down_revision = 'c1ad99c1898e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_code',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('code')
    )

    op.create_table('product_role_code',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=15), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['product_code.code'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_product_role_code_code'), 'product_role_code', ['code'], unique=False)
    op.create_table('product_subscription',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=15), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['product_code.code'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('product_role',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_subscription_id', sa.Integer(), nullable=False),
    sa.Column('product_role_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_role_id'], ['product_role_code.id'], ),
    sa.ForeignKeyConstraint(['product_subscription_id'], ['product_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add master data for product_code and product_role_code
    product_code_table = table('product_code',
                                 column('code', String),
                                 column('desc', String),
                                 column('default', Boolean)
                                 )
    product_role_code_table = table('product_role_code',
                                column('id', Integer),
                                 column('code', String),
                                 column('desc', String),
                                 column('product_code', String)
                                 )
    op.bulk_insert(
        product_code_table,
        [
            {'code': 'PPR', 'desc': 'Personal Property Registry', 'default': False}
        ]
    )
    op.bulk_insert(
        product_role_code_table,
        [
            {'id': 1, 'code': 'search', 'desc': 'Search', 'product_code': 'PPR'},
            {'id': 2, 'code': 'register', 'desc': 'Register', 'product_code': 'PPR'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_role_code_code'), table_name='product_role_code')
    op.drop_table('product_role')
    op.drop_table('product_role_code')
    op.drop_table('product_subscription')
    op.drop_table('product_code')
    # ### end Alembic commands ###
