"""new_corp_types

Revision ID: d2cb317afb6e
Revises: 886fa2608e93
Create Date: 2021-06-11 14:25:01.241730

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Boolean, String
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = 'd2cb317afb6e'
down_revision = '886fa2608e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_size_codes', 'default',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('business_type_codes', 'default',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)

    corp_type_table = table('corp_types',
                            column('code', String),
                            column('description', String),
                            column('default', Boolean)
                            )
    # Insert code values
    op.bulk_insert(
        corp_type_table,
        [
            {'code': 'ULC', 'description': 'BC Unlimited Liability Company', 'default': False},
            {'code': 'LTD', 'description': 'BC Limited Company', 'default': False},
            {'code': 'CCC', 'description': 'BC Community Contribution Company', 'default': False}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_type_codes', 'default',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('business_size_codes', 'default',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.execute("delete from corp_types where code in ('ULC', 'LTD', 'CCC')")
    # ### end Alembic commands ###
