"""added remove permission to user

Revision ID: d34f68927bdf
Revises: ef8a9847f953
Create Date: 2020-05-28 11:23:44.186218

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'd34f68927bdf'
down_revision = 'ef8a9847f953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {'id': '10', 'membership_type_code': 'USER', 'actions': 'REMOVE_BUSINESS'},
            {'id': '11', 'membership_type_code': 'COORDINATOR', 'actions': 'REMOVE_BUSINESS'},
        ]
    )


def downgrade():
    op.execute('delete from permissions where id=10')
    op.execute('delete from permissions where id=11')
