"""Add passcode claimed field

Revision ID: d46ec0214eb2
Revises: 3d13cc3dc30d
Create Date: 2019-08-26 13:18:28.719962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46ec0214eb2'
down_revision = '3d13cc3dc30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('pass_code_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'pass_code_claimed')
    # ### end Alembic commands ###
