"""empty message

Revision ID: e1f06c474e86
Revises: c1902d6e6c8d
Create Date: 2019-08-01 13:48:13.263553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f06c474e86'
down_revision = 'c1902d6e6c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'entity', ['entity_id'], ['id'])
    op.drop_constraint('entity_contact1_id_fkey', 'entity', type_='foreignkey')
    op.drop_constraint('entity_contact2_id_fkey', 'entity', type_='foreignkey')
    op.drop_column('entity', 'contact1_id')
    op.drop_column('entity', 'contact2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('contact2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('contact1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('entity_contact2_id_fkey', 'entity', 'contact', ['contact2_id'], ['id'])
    op.create_foreign_key('entity_contact1_id_fkey', 'entity', 'contact', ['contact1_id'], ['id'])
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'entity_id')
    # ### end Alembic commands ###
