"""adding_view_address_permission

Revision ID: ea64b4d55bfb
Revises: 765d488b18dc
Create Date: 2020-07-16 16:28:44.501658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'ea64b4d55bfb'
down_revision = '765d488b18dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {'id': '17', 'membership_type_code': 'USER', 'actions': 'VIEW_ADDRESS'}
        ]
    )
    op.execute('update org set access_type=\'REGULAR\' where access_type is null')


def downgrade():
    op.execute('delete from permissions where id=17')
