"""Add reset-otp permission

Revision ID: eff007a689cb
Revises: 5cf63f567a62
Create Date: 2020-09-10 10:15:51.454966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = 'eff007a689cb'
down_revision = '5cf63f567a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table('permissions',
                              column('id', sa.Integer()),
                              column('membership_type_code', sa.String(length=15)),
                              column('actions', sa.String(length=100)))

    # Insert code values
    op.bulk_insert(
        permissions_table,
        [
            {'id': '20', 'membership_type_code': 'ADMIN', 'actions': 'RESET_OTP'},
            {'id': '21', 'membership_type_code': 'COORDINATOR', 'actions': 'RESET_OTP'}
        ]
    )


def downgrade():
    op.execute("delete from permissions where actions='RESET_OTP'")
