"""removed deprecated table 

Revision ID: f5deb2ebf9a8
Revises: 2eb11ab005d3
Create Date: 2021-05-07 13:44:06.057924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5deb2ebf9a8'
down_revision = '2eb11ab005d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP table IF EXISTS account_payment_settings ')
    op.execute('DROP table IF EXISTS account_payment_settings_version ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
