"""removed deprecated table 

Revision ID: f5deb2ebf9a8
Revises: 2eb11ab005d3
Create Date: 2021-05-07 13:44:06.057924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5deb2ebf9a8'
down_revision = '2eb11ab005d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_payment_settings')
    op.drop_index('ix_account_payment_settings_version_end_transaction_id', table_name='account_payment_settings_version')
    op.drop_index('ix_account_payment_settings_version_operation_type', table_name='account_payment_settings_version')
    op.drop_index('ix_account_payment_settings_version_transaction_id', table_name='account_payment_settings_version')
    op.drop_table('account_payment_settings_version')
    op.create_index(op.f('ix_activity_logs_org_id'), 'activity_logs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_org_id'), table_name='activity_logs')
    op.create_table('account_payment_settings_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_payment_code', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('bcol_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bcol_account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='account_payment_settings_version_pkey')
    )
    op.create_index('ix_account_payment_settings_version_transaction_id', 'account_payment_settings_version', ['transaction_id'], unique=False)
    op.create_index('ix_account_payment_settings_version_operation_type', 'account_payment_settings_version', ['operation_type'], unique=False)
    op.create_index('ix_account_payment_settings_version_end_transaction_id', 'account_payment_settings_version', ['end_transaction_id'], unique=False)
    op.create_table('account_payment_settings',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preferred_payment_code', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('bcol_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bcol_account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='account_payment_settings_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], name='account_payment_settings_modified_by_id_fkey'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='account_payment_settings_orgs_id_fkey'),
    sa.ForeignKeyConstraint(['preferred_payment_code'], ['payment_types.code'], name='account_payment_settings_preferred_payment_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_payment_settings_pkey')
    )
    # ### end Alembic commands ###
