"""''

Revision ID: f7fe27265ec8
Revises: e1f06c474e86
Create Date: 2019-08-09 10:55:59.613063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fe27265ec8'
down_revision = 'e1f06c474e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('pass_code', sa.String(length=75), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'pass_code')
    # ### end Alembic commands ###
