"""empty message

Revision ID: f91bcb97f2c2
Revises: d1b167ef61da
Create Date: 2020-09-14 10:20:33.647365

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f91bcb97f2c2'
down_revision = 'd1b167ef61da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_login_options_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('account_login_options_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('account_login_options_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('account_payment_settings_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('account_payment_settings_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('account_payment_settings_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('affidavit_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('affidavit_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('affidavit_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('affiliation_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('affiliation_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('affiliation_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('contact_link_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('contact_link_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('contact_link_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('contact_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('contact_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('contact_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('membership_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('membership_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('membership_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('org_settings_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('org_settings_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('org_settings_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('org_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('org_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('org_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_role_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_role_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_role_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_version', sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_version', sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('product_subscription_version', sa.Column('modified_by_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_subscription_version', 'modified_by_id')
    op.drop_column('product_subscription_version', 'modified')
    op.drop_column('product_subscription_version', 'created')
    op.drop_column('product_subscription_role_version', 'modified_by_id')
    op.drop_column('product_subscription_role_version', 'modified')
    op.drop_column('product_subscription_role_version', 'created')
    op.drop_column('org_version', 'modified_by_id')
    op.drop_column('org_version', 'modified')
    op.drop_column('org_version', 'created')
    op.drop_column('org_settings_version', 'modified_by_id')
    op.drop_column('org_settings_version', 'modified')
    op.drop_column('org_settings_version', 'created')
    op.drop_column('membership_version', 'modified_by_id')
    op.drop_column('membership_version', 'modified')
    op.drop_column('membership_version', 'created')
    op.drop_column('contact_version', 'modified_by_id')
    op.drop_column('contact_version', 'modified')
    op.drop_column('contact_version', 'created')
    op.drop_column('contact_link_version', 'modified_by_id')
    op.drop_column('contact_link_version', 'modified')
    op.drop_column('contact_link_version', 'created')
    op.drop_column('affiliation_version', 'modified_by_id')
    op.drop_column('affiliation_version', 'modified')
    op.drop_column('affiliation_version', 'created')
    op.drop_column('affidavit_version', 'modified_by_id')
    op.drop_column('affidavit_version', 'modified')
    op.drop_column('affidavit_version', 'created')
    op.drop_column('account_payment_settings_version', 'modified_by_id')
    op.drop_column('account_payment_settings_version', 'modified')
    op.drop_column('account_payment_settings_version', 'created')
    op.drop_column('account_login_options_version', 'modified_by_id')
    op.drop_column('account_login_options_version', 'modified')
    op.drop_column('account_login_options_version', 'created')
    # ### end Alembic commands ###
