openapi: 3.0.0
info:
  title: Notify API Reference
  description: BC Registries Notify API reference documentation
  version: 1.0.0
paths:
  /api/v1/notify:
    get:
      tags:
        - Notification
      summary: Get Notification details
      description: Get Notification details
      operationId: Get_Notification
      parameters:
        - name: notification_id
          in: path
          description: Notification Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                notify_1:
                  value: '1'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                notify_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                notify_1:
                  value: 'GET, POST'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                notify_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id
                  requestDate:
                    type: string
                    description: request date
                  sentDate:
                    type: string
                    description: sent date
                  recipients:
                    type: string
                    description: recipient emails
                  contents:
                    type: object
                    properties:
                      subject:
                        type: string
                        description: email subject
              examples:
                notify_1:
                  value:
                    - id: 1
                      recipients: string
                      requestDate: '2019-09-25T09:08:57.515479+00:00'
                      sentDate: '2019-09-26T09:34:34.792527+00:00'
                      notifyType:
                        code: EMAIL
                        desc: The Email type of notification
                      notifyStatus:
                        code: DELIVERED
                        desc: Status for the notification sent successful
                      contents:
                        subject: test notify
                        body: 'hello world!'
                    - id: 2
                      recipients: string
                      requestDate: '2019-09-27T09:08:57.515479+00:00'
                      sentDate: '2019-09-27T09:34:34.792527+00:00'
                      notifyType:
                        code: EMAIL
                        desc: The Email type of notification
                      notifyStatus:
                        code: DELIVERED
                        desc: Status for the notification sent successful
                      contents:
                        subject: test notify2
                        body: 'hello world2!'
        '422':
          description: BadRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: Identifier representing the type of error that occurred.
                  message:
                    type: string
                    description: Description of the error.
                description: Contains details of an error that was encountered.
                x-examples:
                  example-1: {}
    post:
      tags:
        - Notification
      summary: Receive Notification
      description: Receive Notification
      operationId: Receive_Notification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                recipients:
                  type: string
                  description: recipient emails
                contents:
                  type: object
                  properties:
                    subject:
                      type: string
                      description: email subject
                    body:
                      type: string
                      description: email body
                    attachment_name:
                      type: string
                      description: attachment
                    attachment_url:
                      type: string
                      description: attachment link
            examples:
              notify_post_1:
                value: '{ "recipients": "test@abc.com", "contents": { "subject": "test notify", "body": "hello world!", "attachmentName": "", "attachmentBytes": "", "attachmentUrl": "" } }'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id
                  requestDate:
                    type: string
                    description: request date
                  sentDate:
                    type: string
                    description: sent date
                  recipients:
                    type: string
                    description: recipient emails
                  contents:
                    type: object
                    properties:
                      subject:
                        type: string
                        description: email subject
              examples:
                notify_post_1:
                  value: '{ "id": 1, "recipients": "test@abc.com", "requestDate": "2019-09-25T09:08:57.515479+00:00", "sentDate": "2019-09-26T09:34:34.792527+00:00", "recipients": "string", "notifyType": { "code": "EMAIL", "desc": "The Email type of notification" }, "notifyStatus": { "code": "PENDING", "desc": "Status for the notification pending" }, "contents": { "subject": "test notify", "body": "hello world!" } }'
        '422':
          description: BadRequest
          content:
            application/json:
              schema:
                title: HTTPValidationError
                type: object
                properties:
                  errors:
                    type:
                      - string
                      - object
                    properties:
                      body:
                        type: string
                x-examples:
                  example-1:
                    errors:
                      - body:
                          - string
              examples:
                example-1:
                  value:
                    errors:
                      - body:
                          - string
  '/api/v1/notify/notifications/:status':
    get:
      tags:
        - Notification
      summary: Get Notifications by status
      description: Get Notification by status
      operationId: Get_Notifications_status
      parameters:
        - name: status
          in: path
          description: Notification status
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                notify_1:
                  value: '1'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                notify_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                notify_1:
                  value: 'GET, POST'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                notify_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: id
                    requestDate:
                      type: string
                      description: request date
                    sentDate:
                      type: string
                      description: sent date
                    recipients:
                      type: string
                      description: recipient emails
                    contents:
                      type: object
                      properties:
                        subject:
                          type: string
                          description: email subject
              examples:
                notify_1:
                  value: '{ "id": 1, "recipients": "test@abc.com", "requestDate": "2019-09-25T09:08:57.515479+00:00", "sentDate": "2019-09-26T09:34:34.792527+00:00", "recipients": "string", "notifyType": { "code": "EMAIL", "desc": "The Email type of notification" }, "notifyStatus": { "code": "DELIVERED", "desc": "Status for the notification sent successful" }, "contents": { "subject": "test notify", "body": "hello world!" } }'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: Identifier representing the type of error that occurred.
                  message:
                    type: string
                    description: Description of the error.
                description: Contains details of an error that was encountered.
                x-examples:
                  example-1: {}
    parameters:
      - name: notification_id
        in: path
        required: true
        schema:
          type: string
        examples:
          notify_1:
            value: 1
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Identifier representing the type of error that occurred.
        message:
          type: string
          description: Description of the error.
      description: Contains details of an error that was encountered.
      x-examples:
        example-1: {}
    NotifyRequest:
      type: object
      properties:
        recipients:
          type: string
          description: recipient emails
        contents:
          type: object
          properties:
            subject:
              type: string
              description: email subject
            body:
              type: string
              description: email body
            attachment_name:
              type: string
              description: attachment
            attachment_url:
              type: string
              description: attachment link
    NotifyResponse:
      type: object
      properties:
        id:
          type: integer
          description: id
        requestDate:
          type: string
          description: request date
        sentDate:
          type: string
          description: sent date
        recipients:
          type: string
          description: recipient emails
        contents:
          type: object
          properties:
            subject:
              type: string
              description: email subject
    ContentsRequest:
      type: object
      properties:
        subject:
          type: string
          description: email subject
        body:
          type: string
          description: email body
        attachment_name:
          type: string
          description: attachment
        attachment_url:
          type: string
          description: attachment link
    ContentsResponse:
      type: object
      properties:
        subject:
          type: string
          description: email subject
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        errors:
          type:
            - string
            - object
          properties:
            body:
              type: string
      x-examples:
        example-1:
          errors:
            - body:
                - string
