<template>
  <v-dialog
    v-model="isDialogOpen"
    content-class="learn-more-dialog"
    :fullscreen="$vuetify.breakpoint.xs || $vuetify.breakpoint.sm"
  >
    <v-card
      class="learn-more-content d-flex"
    >
      <!-- Left Panel -->
      <div class="left-panel pa-8">
        <div class="body-2 font-weight-bold text-uppercase text--secondary mb-5">
          Authentication Options
        </div>
        <h1 class="mb-8">
          BCeID and 2-factor authentication app
        </h1>
        <ul class="mb-11">
          <li class="mb-5">
            Uses your BCeID and a 2-factor authentication app that generates a verification code on your phone.
          </li>
          <li class="mb-5">
            You will need to enter your BCeID username and password to log in.
          </li>
          <li>In addition to your password, you’ll also need a code generated by authenticator app on your phone.</li>
        </ul>
        <v-btn
          large
          block
          color="primary"
          class="font-weight-bold"
          @click="select()"
        >
          SELECT
        </v-btn>
      </div>

      <v-divider vertical />

      <!-- Right Panel -->
      <div class="right-panel pa-8">
        <h2 class="mt-n1 mb-8">
          How It works
        </h2>
        <ul class="steps">
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="mobileDownloadImageSrc"
                alt="Download an authenticator app"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Download an authenticator app such as Microsoft or Google Authenticator.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="createAccountImageSrc"
                alt="Create an account or login with a BCeID"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Create a Basic BCeID account OR use an existing BCeID account.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="loginFormImageSrc"
                alt="Create an account or login with a BCeID"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Log in with your BCeID username and password.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="qrCodeImageSrc"
                alt="Register authenticator"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Open the authentication app and scan the QR code on the website.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="desktopCodeImageSrc"
                alt="Enter a one-time password"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Enter the one-time code you receive in your authenticator app into the website.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="userProfileImageSrc"
                alt="Agree to terms and create user profile"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3 mb-8">
                Agree to terms of use, create user profile.
              </div>
            </div>
          </li>
          <li>
            <div class="step-content">
              <v-img
                class="step-img"
                :src="successImageSrc"
                alt="BCeID and 2-factor Authentication Step 7"
              >
                <template #placeholder>
                  <v-row
                    class="fill-height ma-0"
                    align="center"
                    justify="center"
                  >
                    <v-progress-circular
                      indeterminate
                      color="grey"
                    />
                  </v-row>
                </template>
              </v-img>
              <div class="step-line mt-2" />
              <div class="step-text body-2 mt-3">
                Continue to BC Registries.
              </div>
            </div>
          </li>
        </ul>
      </div>
      <v-btn
        large
        icon
        class="close-btn"
        @click="close()"
      >
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import { Component, Emit, Vue } from 'vue-property-decorator'

@Component({})
export default class LearnMoreBCEID extends Vue {
  isDialogOpen = false

  readonly mobileDownloadImageSrc = new URL('@/assets/img/learn-more/mobile-download.jpg', import.meta.url).href
  readonly createAccountImageSrc = new URL('@/assets/img/learn-more/create-account.jpg', import.meta.url).href
  readonly loginFormImageSrc = new URL('@/assets/img/learn-more/login-form.jpg', import.meta.url).href
  readonly qrCodeImageSrc = new URL('@/assets/img/learn-more/qr-code.jpg', import.meta.url).href
  readonly desktopCodeImageSrc = new URL('@/assets/img/learn-more/desktop-code.jpg', import.meta.url).href
  readonly userProfileImageSrc = new URL('@/assets/img/learn-more/user-profile.jpg', import.meta.url).href
  readonly successImageSrc = new URL('@/assets/img/learn-more/success.jpg', import.meta.url).href

  public open () {
    this.isDialogOpen = true
  }

  public close () {
    this.isDialogOpen = false
  }

  @Emit('bceid-selected')
  select () {
    this.close()
  }
}
</script>

<style lang="scss" scoped>
  $step-content-width: 10.5rem;

  ::v-deep .learn-more-dialog {
    max-width: 1400px;
  }

  .learn-more-content {
    flex-direction: row;

    .left-panel {
      flex: 0 0 auto;
      width: 25rem;
    }
  }

  .v-dialog--fullscreen .learn-more-content {
    flex-direction: column;
    border-radius: 0 !important;

    .left-panel {
      flex: 1 1 auto;
      width: auto;
      border-bottom: 1px solid var(--v-grey-lighten2)
    }
  }

  .steps {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    margin: 0 -1rem;
    padding: 0;
    list-style-type: none;

    li {
      flex: 0 0 auto;
      position: relative;
      margin: 0 2rem;
      vertical-align: top;
    }
  }

  .step-content {
    width: $step-content-width;
    margin: 0 auto;
  }

  .step-img {
    width: $step-content-width;
    height: $step-content-width;
  }

  .step-text {
    text-align: center;
  }

  .step-line {
    position: relative;
    height: 8px;
    background: gold;

    &::before {
      content: ' ';
      position: absolute;
      bottom: 0;
      left: -3rem;
      width: 2rem;
      height: 8px;
      background: #666;
    }

    &::after {
      content: ' ';
      position: absolute;
      left: -1.5rem;
      bottom: -7px;
      width: 1rem;
      height: 22px;
      border-style: solid;
      border-width: 11px 0 11px 11px;
      border-color: transparent transparent transparent #666;
    }
  }

  .steps li:first-child {
    .step-line {
      &::before,
      &::after {
        display: none;
      }
    }
  }

  .close-btn {
    position: absolute;
    top: 1rem;
    right: 1rem;
  }
</style>
