# extend the official jenkins slave base image
FROM openshift/jenkins-slave-base-centos7

# specify wanted version of python
ENV PYTHON_VERSION=3.7.3 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    PIP_NO_CACHE_DIR=off

ENV NPM_CONFIG_PREFIX=$HOME/.npm-global \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH

ARG NODE_VERSION=10.15.3
ARG YARN_VERSION=1.15.2

USER root

# In order to drop the root user, we have to make some directories world
# writable as OpenShift default security model is to run the container under
# random UID.
RUN mkdir -p /opt/app-root

# install python
RUN INSTALL_PKGS="gcc make openssl-devel wget bzip2-devel libffi-devel" \
    && yum install -y $INSTALL_PKGS \
    && cd /tmp \
    && wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
    && tar xf Python-${PYTHON_VERSION}.tgz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations \
    && make altinstall \
    && cd .. \
    && rm -rf Python-${Python_VERSION} \
    && yum remove -y --setopt=tsflags=noscripts $INSTALL_PKGS \
    && yum clean all \
    && pip3.7 install --upgrade pip setuptools \
    && pip3.7 install virtualenv \
    && virtualenv /opt/app-root \
    && source /opt/app-root/bin/activate \
    && pip install flake8 pylint pytest coverage pytest-cov


RUN curl -fsSL https://rpm.nodesource.com/setup_10.x | bash - && \
    curl -fsSL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    INSTALL_PKGS="nodejs-${NODE_VERSION} gcc-c++ make yarn-${YARN_VERSION}" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    # rpm -V $INSTALL_PKGS && \
    yum clean all -y && \
    rm -rf /var/cache/yum/*

RUN chown -R 1001:0 /opt/app-root && \
    chmod -R og+rwx /opt/app-root

USER 1001