---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-${TAG_NAME}-deployment-template
  annotations:
    description:
      Deployment template for an API application and connect to database.
    tags: FastAPI
    iconClass: icon-python
objects:
  - kind: ExternalNetwork
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}-external
      network: ${NAME}-${TAG_NAME}
      labels:
        name: ${NAME}-${TAG_NAME}
        network: ${NAME}-${TAG_NAME}
        app: ${NAME}
    spec:
      description: |
        Define the network parameters for accessing remote resources.
      entries:
        - - ${OIDC_SERVICE}
          - ${SENTRY_SERVICE}
      servicePorts:
        - tcp/443

  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}-to-external
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
    spec:
      description: |
        Allow the application's API to talk to either the database, plus a defined set of external resources.
      source:
        - - role=${ROLE}
          - app=${NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
      destination:
        - - ext:name=${NAME}-external

  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}-to-db
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
    spec:
      description: |
        Allow the application's API to talk to either the database, plus a defined set of external resources.
      source:
        - - role=${ROLE}
          - app=${NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
      destination:
        - - role=db
          - app=${DATABASE_NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}

  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: pods-to-api
      labels:
        name: pods-to-api
        app: ${NAME}
    spec:
      description: |
        Allow pods to talk to the internal api so deployments work.
        This only needs to be specified once per environment.
      source:
        - - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
      destination:
        - - int:network=internal-cluster-api-endpoint

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG_NAME}
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
        role: ${ROLE}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: "[{name: ${DATABASE_NAME}-${TAG_NAME}, kind: Service}]"
    spec:
      ports:
        - name: ${NAME}-${TAG_NAME}-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}-${TAG_NAME}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG_NAME}
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
        role: ${ROLE}
      annotations:
        haproxy.router.openshift.io/ip_whitelist: ${ALLOW_LIST}
    spec:
      host: ${APPLICATION_DOMAIN}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: ${NAME}-${TAG_NAME}-tcp
      to:
        kind: Service
        name: ${NAME}-${TAG_NAME}
        weight: 100

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG_NAME}
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
        role: ${ROLE}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-${TAG_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${NAMESPACE_NAME}-${IMAGE_NAMESPACE}
              name: ${NAME}:${TAG_NAME}
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}-${TAG_NAME}
      template:
        metadata:
          name: ${NAME}-${TAG_NAME}
          labels:
            name: ${NAME}-${TAG_NAME}
            app: ${NAME}
            role: ${ROLE}
        spec:
          containers:
            - name: ${NAME}-${TAG_NAME}
              image:
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 3
                timeoutSeconds: 30
                httpGet:
                  path: /ops/readyz
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 120
                timeoutSeconds: 30
                httpGet:
                  path: /ops/healthz
                  port: 8080

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}-${TAG_NAME}
      labels:
        name: ${NAME}-${TAG_NAME}
        app: ${NAME}
        role: ${ROLE}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${NAME}-${TAG_NAME}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: notify-api

  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: api

  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: 6e0e49

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: tools

  - name: DATABASE_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: postgresql-notify

  - name: OIDC_SERVICE
    displayName: OIDC HOST name
    description: OIDC HOST name.
    required: false
    value: dev.oidc.gov.bc.ca

  - name: SENTRY_SERVICE
    displayName: OIDC HOST name
    description: OIDC HOST name.
    required: false
    value: sentry.io

  - name: NATS_SERVICE
    displayName: NATS Service name
    description: NATS Service name.
    required: false
    value: nats.aaaa.svc

  - name: APPLICATION_DOMAIN
    displayName: Application Domain
    description: The endpoint used for routing access to the application.
    value: notify-api-dev.apps.silver.devops.gov.bc.ca

  - name: ALLOW_LIST
    displayName: Allow List
    description: The allow list containing all of the trusted source IPs.
    required: false

  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "1"

  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "1"

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m

  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi

  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
