name: ACCOUNT UI CI

on:
  pull_request:
    branches:
      - main
      - feature*
    paths:
      - "auth-web/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./auth-web

jobs:
  account-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: "20.5.1"
      app_name: "account-ui"
      working_directory: "./auth-web"
      codecov_flag: "authweb"