name: Auth API CD

on:
  push:
    branches:
      - development
      - master
    paths:
      - "auth-api/**"
  workflow_dispatch:
    inputs:
      environement:
        description: "Environment (dev/test)"
        required: true
        default: "dev"

jobs:
  auth-api-cd:
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/sbc-auth'
    steps:
      - uses: actions/checkout@v2
      - name: Set env by input
        run: |
          echo "::set-env name=TAG_NAME::${{ github.event.inputs.environement }}"

      - name: Set env by master branch
        if: env.TAG_NAME == '' && github.ref == 'refs/heads/master'
        run: |
          echo "::set-env name=TAG_NAME::test"

      - name: Set env by development branch
        if: env.TAG_NAME == '' && github.ref == 'refs/heads/development'
        run: |
          echo "::set-env name=TAG_NAME::dev"

      - uses: pwei1018/bcrs-cd-action@1.1.0
        with:
          WORKING_DIRECTORY: "./auth-api"
          APP_NAME: "auth-api"
          VAULTS: '[{ \"vault\": \"shared\", \"application\": [\"keycloak\", \"jwt\"]}, {\"vault\": \"relationship\",\"application\": [\"postgres-auth\", \"auth-api\", \"sentry\"]}]'
          SKIP_OP: "false"
          OP_PARAMETERS: ${{ secrets.OP_PARAMETERS }}
          OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
          OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_DOCKER_REGISTRY }}
          OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
          OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*Auth API Built and Deployed to ${{env.TAG_NAME}}*"
          channel: "#registries-bot"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
