#When do we want to deploy to Test environment
name: Test Check CI

on:
  pull_request:
    branches:
      - master
    paths:
      - "auth-api/**"
      - "notify-api/**"
      - "status-api/**"
      - "auth-web/**"

jobs:
  master-pr-notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: success()
        with:
          type: ${{ job.status }}
          job_name: "*This Relationship team PR will deploy to Test*: ${{ github.event.pull_request.title }}"
          channel: "#registries"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
