name: Notify API BUILD/DEPLOY CI/CD

on:
  push:
    branches:
      - development

env:
  IMAGE_NAME: notify-api-gh
  TAG_NAME: dev

jobs:
  notify-api-build-depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ secrets.OPENSHIFT_REGISTRY }} -u ${{ secrets.OPENSHIFT_SA_NAME}} --password-stdin

      - name: Build image
        working-directory: ./notify-api
        run: docker build . --file Dockerfile --tag image

      - name: Push image
        working-directory: ./notify-api
        run: |
          IMAGE_ID=${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/$IMAGE_NAME
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "gh-test" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker image tag $IMAGE_ID:$VERSION $IMAGE_ID:$TAG_NAME
          docker push $IMAGE_ID:$TAG_NAME
      - name: Install openshift cli
        working-directory: ./notify-api
        run: |
          sudo curl -sLo /tmp/oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          sudo tar xzvf /tmp/oc.tar.gz -C /tmp/
          sudo mv /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin/
          sudo rm -rf /tmp/oc.tar.gz /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
          sudo chmod +x /usr/local/bin/oc
          oc version
      - name: Login Openshift
        working-directory: ./notify-api
        run: |
          oc ${{ secrets.oc_parameters }}
          oc project ${{ secrets.OPENSHIFT_REPOSITORY_DEV }}
      - name: Install Jq and 1password cli
        working-directory: .
        run: |
          sudo apt install curl unzip jq --yes
          sudo curl -o 1password.zip https://cache.agilebits.com/dist/1P/op/pkg/v0.8.0/op_linux_amd64_v0.8.0.zip
          sudo unzip 1password.zip -d /usr/local/bin
          sudo rm 1password.zip
          sudo chmod +x /usr/local/bin/op
      - name: Set Deployment Environement Variables
        working-directory: .
        run: |
          op --version
          vaults='[{ "vault": "shared", "application": ["email"]}, {"vault": "relationship","application": ["postgres-notify", "notify-api"]}]'
          ./setenv_deploy.sh ${{ secrets.op_parameters }} -e "dev" -v "${vaults}" -c "dc/notify-api-gh-dev"
      - name: Rollout new deployment
        working-directory: ./notify-api
        run: |
          oc rollout latest dc/$IMAGE_NAME-$TAG_NAME
          oc rollout status dc/$IMAGE_NAME-$TAG_NAME -w
