#When do we want to deploy to Test environment
name: Test PR CI

on:
  pull_request:
    branches:
      - master

jobs:
  move-to-test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*This Relationship team PR will deploy to Test*: ${{ github.event.pull_request.title }}"
          channel: "#relationship-developers"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
