name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 1password/op
    steps:
    - uses: actions/checkout@v1
    - name: Set up Env
      run: |
        op --version
        . ./1pass/setenv_1pass.sh ${{secrets.op_username}} ${{secrets.op_secret_key}} ${{secrets.op_password}}
        env

